name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - env: dev
            url: https://dev.gcn.nasa.gov
          - env: test
            url: https://test.gcn.nasa.gov
          - env: prod
            url: https://gcn.nasa.gov
    environment:
      name: ${{ matrix.env }}
      url: ${{ matrix.url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          force_push_tag: true
          tag: ${{ matrix.env }}
